### ISSUE TITLE
Rename from webrtc-rs-rtcp to rtcp

### ISSUE THREAD

**Issue by metaclips** [webrtc-rs/rtcp#2]
Rename library on cargo from webrtc-rs-rtcp to rtcp as name has not been taken https://crates.io/search?q=rtcp

**Comment by rainliu** [comment]
I still prefer webrtc-rs-rtcp to rtcp, in order to keep consistent naming as other libraries. 

you can do like this:

[dependencies]
util = { package = "webrtc-rs-util", version = "0.1.0" }
rtp = { package = "webrtc-rs-rtp", version = "0.1.0" }
rtcp = { package = "webrtc-rs-rtcp", version = "0.1.0" }
